kind: pipeline
type: docker
name: default

steps:

- name: aspell
  image: facteurpat/aspell:latest
  commands:
  - bash ./aspell/check.sh
  - mkdir -p ./build

- name: pandoc
  image: pandoc/latex:latest
  commands:
  - cd ./pandoc
  - bash ./build.sh pdf
  - bash ./build.sh docx
  - cd ..
  - ls -ltr ./pandoc


- name: test
  image: alpine
  commands:
  - echo bonjour
  - ls -la .

