kind: pipeline
type: docker
name: default

steps:

- name: get_commit
  image: alpine/git
  commands:
  - alpine/git rev-parse --short HEAD > commit.txt
  - 'cat commit.txt'

- name: aspell
  image: facteurpat/aspell:latest
  commands:
  - cat ./aspell/lang.txt
  - bash ./aspell/check.sh
  - mkdir -p ./build

- name: pandoc
  image: pandoc/latex:latest
  commands:
  - cd ./pandoc
  - 'sh ./build.sh pdf $(cat ../NAME.md)_$(cat ../commit.txt)'
  - cd ..
  - ls -ltr ./pandoc
