kind: pipeline
type: docker
name: default

steps:

- name: get_commit
  image: alpine/git
  commands:
  - git rev-parse --short HEAD > commit.txt
  - 'cat commit.txt'

- name: aspell
  image: facteurpat/aspell:latest
  commands:
  - cat ./aspell/lang.txt
  - bash ./aspell/check.sh

- name: reqflow
  image: alpine
  commands:
  - echo Suivi des exigences avec Reqflow

- name: pandoc
  image: pandoc/latex:latest
  commands:
  - COMMIT=$(cat ./commit.txt)
  - NAME=$(cat ./NAME.md)
  - BUILDNAME=$NAME-$COMMIT
  - cd ./pandoc
  - 'sh ./build.sh pdf $BUILDNAME'
  - 'sh ./build.sh docx $BUILDNAME'
  - cd ..
  - ls -ltr ./pandoc

- name: mkdocs
  image: squidfunk/mkdocs-material:latest
  commands:
  - /usr/local/bin/mkdocs build
  - ls -ltr .

- name: package
  image: alpine
  commands:
  - COMMIT=$(cat ./commit.txt)
  - NAME=$(cat ./NAME.md)
  - BUILDFOLDER=build-$COMMIT
  - BUILDNAME=$NAME-$COMMIT
  - mkdir -p $BUILDFOLDER
  - cp mispelled.txt $BUILDFOLDER
  - cp pandoc/$BUILDNAME.pdf $BUILDFOLDER
  - cp pandoc/$BUILDNAME.docx $BUILDFOLDER
  - ls -ltr $BUILDFOLDER

- name: deploy-scp-web
  image: appleboy/drone-scp
  settings:
    host: 192.168.0.21
    user: nginx
    password: nginx
    port: 22
    target: /www/data/site
    source: ./site/*

- name: release-gitea
  image: alpine
  commands:
  - echo release gitea

