kind: pipeline
type: docker
name: default

steps:

- name: get_commit
  image: alpine/git
  commands:
  - git rev-parse --short HEAD > commit.txt
  - 'cat commit.txt'

- name: aspell
  image: facteurpat/aspell:latest
  commands:
  - cat ./aspell/lang.txt
  - bash ./aspell/check.sh

- name: pandoc
  image: pandoc/latex:latest
  commands:
  - COMMIT=$(cat ./commit.txt)
  - echo $COMMIT
  - NAME=$(cat ./NAME.md)
  - echo $NAME
  - BUILDNAME=$NAME-$COMMIT
  - echo $BUILDNAME
  - cd ./pandoc
  - 'sh ./build.sh pdf $BUILDNAME'
  - 'sh ./build.sh docx $BUILDNAME'
  - cd ..
  - ls -ltr ./pandoc

- name: package
  image: alpine
  commands:
  - COMMIT=$(cat ./commit.txt)
  - echo $COMMIT
  - NAME=$(cat ./NAME.md)
  - echo $NAME
  - BUILDFOLDER=build-$COMMIT
  - echo $BUILDFOLDER
  - BUILDNAME=$NAME-$COMMIT
  - echo $BUILDNAME
  - mkdir -p $BUILDFOLDER
  - cp mispelled.txt $BUILDFOLDER
  - cp pandoc/$BUILDNAME.pdf $BUILDFOLDER
  - cp pandoc/$BUILDNAME.docx $BUILDFOLDER
  - ls -ltr $BUILDFOLDER

