---
kind: pipeline
type: docker
name: test
steps:

- name: get_commit
  image: alpine/git
  commands:
  - git rev-parse --short HEAD > commit.txt
  - 'cat commit.txt'

- name: aspell_assets
  image: alpine/git
  commands:
  - git clone http://192.168.0.21:3000/kevin/madoc-aspell.git aspell

- name: aspell
  image: facteurpat/aspell:latest
  commands:
  - cat ./aspell/lang.txt
  - bash ./aspell/check.sh

- name: reqflow
  image: alpine
  commands:
  - echo Suivi des exigences avec Reqflow
  - echo "A mettre en place!" > ./reqflow.txt

- name: pack
  image: alpine
  commands:
  - COMMIT=$(cat ./commit.txt)
  - NAME=$(cat ./NAME.md)
  - mkdir -p ./test
  - cp aspell.txt ./test/aspell-$COMMIT.txt
  - cp reqflow.txt ./test/reqflow-$COMMIT.txt
  - ls -ltr ./test

- name: upload
  image: appleboy/drone-scp
  settings:
    host:
      - 192.168.0.21
    username:
      from_secret: drone_user
    password:
      from_secret: drone_pass
    port: 22
    command_timeout: 4m
    target: /www/data/madoc
    source:
      - ./test/*

- name: release
  image: plugins/gitea-release
  settings:
    base_url: http://192.168.0.21:3000
    api_key: 7073fe81a3cc1c60bc01d01ceb24d6bb87f8ea43
    files: /drone/src/test/*
    insecure: true
  when:
    event: tag

---
kind: pipeline
type: docker
name: build
steps:

- name: get_commit
  image: alpine/git
  commands:
  - git rev-parse --short HEAD > commit.txt
  - 'cat commit.txt'

- name: mkdocs
  image: squidfunk/mkdocs-material:latest
  commands:
  - /usr/local/bin/mkdocs build
  - ls -ltr .

- name: pandoc_assets
  image: alpine/git
  commands:
  - git clone http://192.168.0.21:3000/kevin/madoc-pandoc.git pandoc

- name: pandoc
  image: pandoc/latex:latest
  commands:
  - COMMIT=$(cat ./commit.txt)
  - NAME=$(cat ./NAME.md)
  - BUILDNAME=$NAME-$COMMIT
  - cd ./pandoc
  - 'sh ./build.sh pdf $BUILDNAME'
  - 'sh ./build.sh docx $BUILDNAME'
  - cd ../
  - ls -ltr ./pandoc

- name: pack
  image: alpine
  commands:
  - COMMIT=$(cat ./commit.txt)
  - NAME=$(cat ./NAME.md)
  - BUILDNAME=$NAME-$COMMIT
  - mkdir -p ./build
  - cp ./pandoc/$BUILDNAME.pdf ./build
  - cp ./pandoc/$BUILDNAME.docx ./build
  - tar zcvf $BUILDNAME-mkdocs.tgz site/
  - cp -r $BUILDNAME-mkdocs.tgz ./build
  - ls -ltr ./build

- name: upload
  image: appleboy/drone-scp
  settings:
    host:
      - 192.168.0.21
    username:
      from_secret: drone_user
    password:
      from_secret: drone_pass
    port: 22
    command_timeout: 4m
    target: /www/data/madoc
    source:
      - ./build/*.pdf
      - ./build/*.docx
      - ./site/*

- name: release
  image: plugins/gitea-release
  settings:
    base_url: http://192.168.0.21:3000
    api_key: 7073fe81a3cc1c60bc01d01ceb24d6bb87f8ea43
    files: /drone/src/build/*
    insecure: true
  when:
    event: tag
