kind: pipeline
type: docker
name: default

steps:

- name: get_commit
  image: alpine/git
  commands:
  - git rev-parse --short HEAD > commit.txt
  - 'cat commit.txt'

- name: aspell
  image: facteurpat/aspell:latest
  commands:
  - cat ./aspell/lang.txt
  - bash ./aspell/check.sh

- name: reqflow
  image: alpine
  commands:
  - echo Suivi des exigences avec Reqflow

- name: pandoc
  image: pandoc/latex:latest
  commands:
  - COMMIT=$(cat ./commit.txt)
  - NAME=$(cat ./NAME.md)
  - BUILDNAME=$NAME-$COMMIT
  - cd ./pandoc
  - 'sh ./build.sh pdf $BUILDNAME'
  - 'sh ./build.sh docx $BUILDNAME'
  - cd ..
  - ls -ltr ./pandoc

- name: mkdocs
  image: squidfunk/mkdocs-material:latest
  commands:
  - /usr/local/bin/mkdocs build
  - ls -ltr .

- name: package
  image: alpine
  commands:
  - COMMIT=$(cat ./commit.txt)
  - NAME=$(cat ./NAME.md)
  - BUILDFOLDER=build-$COMMIT
  - BUILDNAME=$NAME-$COMMIT
  - mkdir -p $BUILDFOLDER
  - cp mispelled.txt $BUILDFOLDER
  - cp pandoc/$BUILDNAME.pdf $BUILDFOLDER
  - cp pandoc/$BUILDNAME.docx $BUILDFOLDER
  - ls -ltr $BUILDFOLDER

- name: deploy-web
  image: appleboy/drone-scp
  settings:
    host: 192.168.0.21
    key: "-----BEGIN OPENSSH PRIVATE KEY----- b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn NhAAAAAwEAAQAAAYEA1TAGZ0Xhp6Zg3TZ31/4CYCdMsoROf4j/MJzEo9ebrJX8IbZ8SrQu lvBhvOXpbTIF4FJl/RohJxqlBXNYA5decU/ZLyOvRQKIa6z7uLejbIxDfrwM29Jifg357p 5PqNdmATmpmC3tsssmjJ118EoBuqvi3f+VZyvphODRbsVbkuz4H3vMnU2PYqExpuGroeKn iM7/1SrHKT/XTQiNUzvKFbGJgYKSeT9vM6Zh2qV1fxEYDfX+zb9vnUr123FXnBySMsdhAY lHeu5z7IwyyLZgqmg7sMKuBN4i0mnNgYw3E5Um+NxQdJELtvaw2J0TcdeX3JlKgFzpas2Q qBkX2JjCWrjaXQDneVyDIuyAPRHXQSfIjgt84j9cUKhhyP+A0SM/DnPCv+8smZjRNE6OIz ok9EBsDdAbTGheeeNSjuP8OOXMQFuGcvNeTOjYdaquoc+XppIejNuEVtfBQrGs7bXx/xxQ jzHy8pqzUrMQmyCZzY56RnIEve2P3HS6JpAhj6XPAAAFgKoj1WKqI9ViAAAAB3NzaC1yc2 EAAAGBANUwBmdF4aemYN02d9f+AmAnTLKETn+I/zCcxKPXm6yV/CG2fEq0LpbwYbzl6W0y BeBSZf0aIScapQVzWAOXXnFP2S8jr0UCiGus+7i3o2yMQ368DNvSYn4N+e6eT6jXZgE5qZ gt7bLLJoyddfBKAbqr4t3/lWcr6YTg0W7FW5Ls+B97zJ1Nj2KhMabhq6Hip4jO/9Uqxyk/ 100IjVM7yhWxiYGCknk/bzOmYdqldX8RGA31/s2/b51K9dtxV5wckjLHYQGJR3ruc+yMMs i2YKpoO7DCrgTeItJpzYGMNxOVJvjcUHSRC7b2sNidE3HXl9yZSoBc6WrNkKgZF9iYwlq4 2l0A53lcgyLsgD0R10EnyI4LfOI/XFCoYcj/gNEjPw5zwr/vLJmY0TROjiM6JPRAbA3QG0 xoXnnjUo7j/DjlzEBbhnLzXkzo2HWqrqHPl6aSHozbhFbXwUKxrO218f8cUI8x8vKas1Kz EJsgmc2OekZyBL3tj9x0uiaQIY+lzwAAAAMBAAEAAAGAORHKJQtIBSE8/Pr/ygptiF/84C 0a9nkuF01gNpwZSHI+NKgtTbI+ZpmjEHZbrqedexeTxdWg2l7/nh3qicuTtLGzajMbUFYF Pw3ntOM0FHLX/q1Io/AF/ciwB3jJymEfJWTSSbLB1wMbJrlgQRsOq3IoIVWyIRRYRwIIDq c2hHZ7VbJGbDW/FKAiMpJm58dNIgqH4gC5oAk/EZggfQ+cYYJNVSYnH94jXqhDucxhT8q7 rcEUnO+KaYkPl9cXpOrgmxPbo+aw3yuFhqPBMswPFOUXlfqJUM/jSzTt78shvpqi7pqvTk FsdYFaXNbx+CA7S1FtFlkmOL60Rvm/dX5U4Ibq6VNQusgEYzVYrjTOyMFZoIj3BDLAPyNx u6/Og0iiCNGXaTiouyU6NO5PgaDpoFUNIKVmQPsClwZsxATark1VTVHWT9Y+X0k72GTvsl XcWMDtSPtbjN1kT2Kg9SVgfkvW2ZUqgNs41Qy0/x2e3DbsNk/Dqr/tD0N1oGFOuvyBAAAA wQDiBk+XERpawLggPhWPAXf6oo91abkiImQrpd+3WWtEB37yVpDQ7nSI44NVEqOC6VqA2R GuvuHOOIiHHJCIcCEBf8+Wm9aN5ZemhW4kSHVkC4PJ81bupWs5P2f8jmiD5Vu7tx9afbHn bqr+ir8OjkuplLwWre9mnV5CvIy/8tlLQWh8eSMBL9UUub4Si3dKztGJKkl3llByCXdX8H C4R+mDDxYj5QUnXvS3oYhrEb6qI/uew+HbImjKsEnfE9cKOPkAAADBAPQ6IjLpQMbor31o +WXsf7gwsHaN52cSEJ27gz5J2rcB01K83m1cT1qPQNDYFWzrYWw8D38dHLHj7g9/ELXJmp /idsnaKhp+X55nkEiVbETbqSN7SGtxFyr4edBcjtqrWH3sjzQiR88YWcOezVUUQxZKGQmi tB7DoQX8hk1fBISLwvisa0PmzFSn2pFXivyzuDZ9hxUYueIPU9hisQZgTC10rtco358b53 MMz7K4kCL7rrG3RmHQu0p9cTK+vRF0pwAAAMEA33bZ1bZAwHL2e2BHaky2Fyk8nq8f3q8t egSoSENjkuj85Yt0sweFC04bqELZnIeJgKNh4YXkCqwK39bAwXwBVzUCzEK55XPOIyMOfN 6E77AhQasPgB5m+Qpc89PxGbwc8SHBVpFyc65D7bPGLQwnMINgl1fpIMjCU280srqRZgWz cOdvrPCUdQymFVeS53M1uanOxbsFK7Fp1/Awq9LwW+wyZCk8GHXmXlfHGO4UQy2ySjHI1E wcX8MmV8I632KZAAAACnJvb3RAdW5nZXI= -----END OPENSSH PRIVATE KEY-----
"
    port: 22
    target: /www/data/site
    source: ./site/*

- name: release-gitea
  image: alpine
  commands:
  - echo release gitea

