kind: pipeline
type: docker
name: default

steps:

- name: aspell-en
  image: starefossen/aspell:latest
  commands:
  - 'for f in `find ./docs -iname "*.md"`; do echo $f: $(cat $f | aspell list); done; > mispelled.txt'
  - cat mispelled.txt

- name: pandoc
  image: pandoc/latex:latest
  commands:
  - pandoc -f markdown -t latex README.md -o README.tex
  - cat README.tex
  - pandoc -f markdown -t html README.md -o README.html
  - cat README.html

- name: test
  image: alpine
  commands:
  - echo bonjour
  - ls -la .

