kind: pipeline
type: docker
name: default

steps:

- name: get_commit
  image: alpine/git
  commands:
  - git rev-parse --short HEAD > commit.txt
  - 'cat commit.txt'

- name: aspell
  image: facteurpat/aspell:latest
  commands:
  - cat ./aspell/lang.txt
  - bash ./aspell/check.sh

- name: pandoc
  image: pandoc/latex:latest
  commands:
  - COMMIT=$(cat ./commit.txt)
  - echo $COMMIT
  - NAME=$(cat ./NAME.md)
  - echo $NAME
  - cd ./pandoc
  - 'sh ./build.sh pdf ${NAME}_${COMMIT}'
  - 'sh ./build.sh docx ${NAME}_${COMMIT}'
  - cd ..
  - ls -ltr ./pandoc

- name: package
  image: alpine
  commands:
  - COMMIT=$(cat ./commit.txt)
  - echo $COMMIT
  - NAME=$(cat ./NAME.md)
  - echo $NAME
  - BUILD_FOLDER=build_$COMMIT
  - echo $BUILD_FOLDER
  - mkdir -p $BUILD_FOLDER
  - cp mispelled.txt $BUILD_FOLDER
  - cp pandoc/$NAME_$COMMIT.pdf $BUILD_FOLDER
  - cp pandoc/$NAME_$COMMIT.docx $BUILD_FOLDER
  - ls -ltr ${BUILD_FOLDER}

