kind: pipeline
type: docker
name: default

steps:

- name: get_commit
  image: alpine
  commands:
  - apk add --no-cache bash git openssh
  - git rev-parse --short HEAD > commit.txt
  - 'cat commit.txt'

- name: aspell
  image: facteurpat/aspell:latest
  commands:
  - bash ./aspell/check.sh
  - mkdir -p ./build

- name: pandoc
  image: pandoc/latex:latest
  commands:
  - cd ./pandoc
  - sh ./build.sh pdf
  - sh ./build.sh docx
  - cd ..
  - ls -ltr ./pandoc
